defaults: &defaults
  docker:
    - image: circleci/node:9
  working_directory: ~/nuxt-styleguide

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create yarn.lock checksum
          command: sha256sum yarn.lock > .yarn-lock-sum
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum ".yarn-lock-sum" }}
      - run:
          name: Install yarn
          command: npm install yarn --no-save
      - run:
          name: Install
          command: $(npm bin)/yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum ".yarn-lock-sum" }}
      - save_cache:
          paths:
            - ~/nuxt-styleguide
          key: v1-repo-{{ .Revision }}
  lint:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
          - v1-repo-{{ .Revision }}
      - run:
          name: Lint
          command: npm run lint
  deploy-gh-pages:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
          - v1-repo-{{ .Revision }}
      - run:
          name: Build
          command: cd demo && $(npm bin)/nuxt generate
      - run:
          name: Checkout gh-pages branch
          command: git clone --depth=1 -b gh-pages https://github.com/sumcumo/nuxt-styleguide.git gh-pages
      - run:
          name: Update gh-pages
          command: mv gh-pages/.git dist/.git && cd dist && git add . && git commit -m'update gh-pages'
      - run:
          name: Push gh-pages branch
          command: cd dist && git push origin gh-pages

workflows:
  version: 2
  deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
      - deploy-gh-pages:
          requires:
            - lint
          filters:
            branches:
              only: master
